name: Deploy Lambda Function

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Create env file
        uses: danielr1996/envsubst-action@1.0.0
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        with:
          input: .env_template
          output: src/.env
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1
      - name: Install dependencies
        run: |
          pip install -r requirements.txt --target src
      - name: Deploy to AWS Lambda
        run: |
          cd src && zip -r ../function.zip .
          aws lambda update-function-code --function-name arn:aws:lambda:us-east-1:318483981372:function:telegram-to-aws-func --zip-file fileb://function.zip