name: Deploy Lambda Function

on:
  # push:
  #   branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Linters
        run: |
          pip install flake8==7.0.0 black==24.4.2 isort==5.13.2
          black --line-length=79 --check .
          isort --profile black --check .
      - name: Create env file
        uses: danielr1996/envsubst-action@1.0.0
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        with:
          input: .env_template
          output: src/.env
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1
      - name: Install dependencies
        run: |
          pip install --platform manylinux2014_x86_64 --only-binary=:all: --python-version 3.10 -r requirements.txt --target src
      - name: Deploy to AWS Lambda
        run: |
          cd src
          zip -r ../function.zip .
          cd ..
          aws lambda update-function-code --function-name $AWS_FUNCTION_NAME --zip-file fileb://function.zip
        env:
          AWS_FUNCTION_NAME: ${{ secrets.AWS_FUNCTION_NAME }}